# Generated by Django 5.2.4 on 2025-07-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('meetup', 'Meetup'), ('networking', 'Networking'), ('festival', 'Festival'), ('concert', 'Concert'), ('exhibition', 'Exhibition'), ('trade_show', 'Trade Show'), ('panel_discussion', 'Panel Discussion'), ('product_launch', 'Product Launch'), ('community_event', 'Community Event'), ('charity_event', 'Charity Event'), ('sports_event', 'Sports Event'), ('cultural_event', 'Cultural Event'), ('educational_event', 'Educational Event'), ('corporate_event', 'Corporate Event'), ('social_event', 'Social Event'), ('wedding', 'Wedding'), ('birthday_party', 'Birthday Party'), ('anniversary', 'Anniversary'), ('family_reunion', 'Family Reunion'), ('graduation', 'Graduation'), ('holiday_party', 'Holiday Party'), ('retirement_party', 'Retirement Party'), ('theater_performance', 'Theater Performance'), ('film_screening', 'Film Screening'), ('art_show', 'Art Show'), ('book_signing', 'Book Signing'), ('food_festival', 'Food Festival'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
